### ISSUE TITLE
only notifies on success

### ISSUE THREAD

**Issue by domkm** [jeluard/boot-notify#2]
I recently created [my first boot project](https://github.com/parenthesis/isomorphiclj/blob/1f6cc24c737378a94cfea16d69ab71461c677dba/build.boot#L48-49) and am using `speak`/`notify` to alert me of test results. `speak` works on both success and failure, but `notify` only works on success.

**Comment by jeluard** [comment]
Sorry just noticed your comment. Looks great! I added a comment to your PR.

**Comment by jeluard** [comment]
Released as part of `0.1.2`.

**Comment by domkm** [comment]
Thanks!
