### ISSUE TITLE
Throw more descriptive errors when CLI deps cannot be found

### ISSUE THREAD

**Issue by martinklepsch** [jeluard/boot-notify#4]

**Comment by jeluard** [comment]
Do you have any suggestions?

**Comment by martinklepsch** [comment]
@jeluard nothing specific. Basically I imagined that it should be checked if the to-be-used executable is present at `$PATH`.

**Comment by jeluard** [comment]
Is that different from the current [check](https://github.com/jeluard/boot-notify/blob/master/src/jeluard/boot_notify.clj#L8) ? Or is it not working properly?

**Comment by martinklepsch** [comment]
@jeluard oh. weird. I added `boot-notify` to a repo and on coworker's computers got a bunch of confusing errors that wen't away after installing. I'll recheck...
